### PR TITLE
Pickup delivery

### PR DESCRIPTION
**Pull request by johndowns**
@JackDownsNZ please test this out

### CODE REVIEW

**Comment by johndowns** [comment]
@JackDownsNZ there is a build failure in the front-end code - can you take a look please

**Comment by JackDownsNZ** [comment]
Cool - tested and all works for me.

**Comment by JackDownsNZ** [comment]
Since Joyce wants to hold these changes till the weekend, should we hold this PR until then? Or do you want me to hide my front end changes so we can push the api changes?

**Comment by johndowns** [comment]
Let's just hold the PR. I may change my mind depending on what other changes get merged though

**Comment by johndowns** [comment]
I'm abandoning this PR since it's been replaced with the new behaviour

**Pull request closed without merging**
