### PR TITLE
Track voucher redemption

### PR DESCRIPTION
**Pull request by johndowns**

### CODE REVIEW

**Comment by johndowns** [comment]
@JackDownsNZ There is a front-end merge conflict with master. Can you please resolve and push?

**Comment by JackDownsNZ** [comment]
Seems to be bug in front end (redeem option not showing). Looking into this now.

**Comment by JackDownsNZ** [comment]
@johndowns it looks like redemptionDate is returning `0001-01-01T00:00:00` instead of null

If you arent able to set to null - I can adapt frontend to set `0001-01-01T00:00:00`

**Comment by johndowns** [comment]
No it should be null. I'll look into it

**Comment by johndowns** [comment]
@JackDownsNZ I've pushed a change to hopefully resolve this. If you see this happen again can you give me the vendor ID and voucher ID please?

**Comment by JackDownsNZ** [comment]
Hm still happening

`customerAcceptsMarketing: false
customerEmailAddress: ""
customerName: "Nikki Tapp"
customerRegion: "Urenui"
lineItemId: "4355384901688"
orderDate: "2020-04-23T10:23:00Z"
orderId: "1930677485624"
orderRef: "#SOSNZ16721"
redemptionDate: "0001-01-01T00:00:00"
voucherDescription: "$25"
voucherFees: 0.8
voucherGross: 25
voucherId: "3BF8-1F6B-0BEB-6AFF-6B8D"
voucherIsDonation: false
voucherNet: 24.2
voucherQuantity: 1`

Using vendor `4349964779576`

**Comment by johndowns** [comment]
OK I will look at this later. If you are able to test the rest of it and see if it all works (apart from that) then I'll try to do any fixes all together when I get a few mins

**Comment by JackDownsNZ** [comment]
Alright no worries

**Comment by johndowns** [comment]
@JackDownsNZ I found the bug on the API and have pushed a fix. Let me know if there are any other issues you discover

**Comment by JackDownsNZ** [comment]
Cool - that works well now.

Ive just gone through and tested.

Setting redemptionDate works fine (redeeming voucher), but when I try to undo (set redemptionDate to null) it gives me a 500 error.

**Comment by johndowns** [comment]
Thanks, found a bug and pushed a fix. Sorry I'm not able to do more testing myself :( Bit tricky today

**Comment by johndowns** [comment]
@JackDownsNZ Please try again now

**Comment by JackDownsNZ** [comment]
Cool all working now! Am adding to Admin view also then will push changes for others to test.

**Comment by JackDownsNZ** [comment]
Note - If a voucher field `voucherIsDonation === true`, the redemption option is hidden.

**Comment by johndowns** [comment]
Nice - is this ok for everyone to test now?

**Comment by JackDownsNZ** [comment]
Yep should be all good - both admin and vendor side.

**Comment by JackDownsNZ** [comment]
@dwdowns @joyceqnz We have added the functionality for vendors to be able to redeem vouchers for their business(es). It's currently live in test (https://soscafevendoruiproxytest.azurewebsites.net/vendors) for both the vendor side and admin side.

Please give it a test and let us know if its all good to go live.

**Comment by dwdowns** [comment]
Awesome – yes please go live 😊

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Pull request merged**
