### PR TITLE
Allow admins to edit more vendor details

### LINKED ISSUE #80: Allow admins to edit everything about the vendor record
Including Business Name, Email Address and Date Registered (not the ID)

### LINKED ISSUE #103: Bug in Portal - not saving Name, combinations
It's hard to work out exactly, but there seem to be times when saving combinations of changes to the portal works, but individual items doesn't eg I think if I just change the business name and save, it doesn't work, but if I change bank account as well, then it works?

### PR DESCRIPTION
**Pull request by johndowns**
Closes #80 , closes #103

### CODE REVIEW

**Comment by johndowns** [comment]
@JackDownsNZ I've done a first cut at the API side of this. Can you please resolve the merge conflicts and then we can test it out?

**Comment by JackDownsNZ** [comment]
Looks like theres a front end bug that didnt come across in local testing - looking into it now

**Comment by JackDownsNZ** [comment]
Alright I'm stuck - it works fine locally (for me at least), but then in test env it throws a Ref error. Will have to take a look at it in the morning, stuck going in circles.

**Comment by JackDownsNZ** [comment]
Sorry stuck with work - it might be best for us to comment out the date changing part for now and commit the rest of the changes so that the admins can change most of the data.

Ill have time this evening/ tomorrow evening to do the date stuff.

@johndowns all good with this?

**Comment by johndowns** [comment]
Yes all good. Can you comment that bit please?

**Comment by JackDownsNZ** [comment]
@johndowns have remove date picker. Was getting 500 error but I assume thats due to this build being overridden by the other PR. Once this is built and pushed to test ill test again.

**Comment by JackDownsNZ** [comment]
Looks like there is a backend and front end conflict. I have fixed frontend but not sure about API side sorry @johndowns.

**Comment by johndowns** [comment]
I've discovered another issue with this (on the back-end side) - editing a business's name doesn't update the list of businesses that a user sees when they log in. I can fix this but I'll need to make some changes later.

**Comment by randiratnayake** [comment]
@johndowns the update views have been aligned on both vendor view and admin view. Due to the formating is done when presenting the data in form control I had to retain the date originally received from server-side to use when post back on update (ISO Format) similar to terms accepted date timestamp.

View model date time stamp type has been changed from a type date to string to avoid converting multiple times. So what receives from the server on load is sent back (w/o update or conversion).

Tested both views and can see it works. Over to the team to test overall.

**Pull request merged**
