### PR TITLE
Add fields for vendor to indicate their open status for each alert level

### PR DESCRIPTION
**Pull request by johndowns**

### CODE REVIEW

**Comment by johndowns** [comment]
@JackDownsNZ it looks like the front-end is sending empty fields as empty strings instead of `false`- so it's not currently working. You ok to fix that up?

**Comment by JackDownsNZ** [comment]
Yep haven't touched it since you added backend stuff. Just placeholder form data at this stage. Will do tomorrow morning.
________________________________

**Comment by JackDownsNZ** [comment]
@johndowns all working on my end. Both in Vendor & Admin view. Can you test also?

**Comment by johndowns** [comment]
Thanks @JackDownsNZ, I ran some tests and looks good to me for the existing vendors.

For new vendors it doesn't appear that the front-end has been updated yet? Do you want to do that in this PR or a separate one?

**Comment by JackDownsNZ** [comment]
@johndowns am testing new business side now, but im getting a 500 error, cant see why

**Comment by johndowns** [comment]
Can you give me some more specific info - what URL is giving you the error and what is the payload you are sending?

**Comment by JackDownsNZ** [comment]
Error is on ${env.apiBaseUrl}/vendors when sending the new vendor form payload since updating fields to include alert level status'

Have pushed my changes so feel free to test to see what I see - very little info in the error.

**Comment by johndowns** [comment]
@JackDownsNZ Looks like this code is still sending strings where booleans are expected. Here's an example payload I got a 500 from:

```json
{
    "businessName": "26Apr JD 1",
    "type": "Food/Beverage",
    "phoneNumber": "0",
    "description": "0",
    "city": "Auckland/North",
    "businessPhotoUrl": "",
    "bankAccountNumber": "00 0000 0000000 00",
    "hasAgreedToTerms": true,
    "isClickAndCollect": false,
    "clickAndCollectUrl": "",
    "level1Closed": true,
    "level2Closed": true,
    "level3Closed": true,
    "level1Delivery": "",
    "level2Delivery": "",
    "level3Delivery": "",
    "level1ClickAndCollect": "",
    "level2ClickAndCollect": "",
    "level3ClickAndCollect": "",
    "level1Open": "",
    "level2Open": "",
    "level3Open": ""
}
```

**Comment by JackDownsNZ** [comment]
Ah found the issue. Submitted fix.

**Comment by johndowns** [comment]
Thanks - looks like we can submit now. I've run a few more tests and it's looking good. @joyceqnz and @dwdowns are you able to test this too please? Please try both creating new test vendors and editing existing vendors. The test site URL is: https://soscafevendoruiproxytest.azurewebsites.net/

**Comment by johndowns** [comment]
@JackDownsNZ one minor wording tweak - "I already have Click & Collect setup" should say "set up" (two words) :)

**Comment by JackDownsNZ** [comment]
Cool fixed. I also added logic to the business detail page that will hide the "interested in setting up C&C" if the C&C url contains data.

Also if they have "interested in setting up C&C" ticked, it will hide the C&C URL box.

**Comment by dwdowns** [comment]
Awesome thank you both. This is still in test, yes?

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
@JackDownsNZ is still pushing changes. Jack, can you let us know when this is stable and ready for David and Joyce to test?

**Comment by JackDownsNZ** [comment]
Sorry! That was the final change, its all good - just had to improve some of the logic with hiding form fields.

**Comment by johndowns** [comment]
@joyceqnz @dwdowns Over to you to test please. http://soscafevendoruiproxytest.azurewebsites.net/

**Comment by dwdowns** [comment]
We just did and it looks good thanks 😊

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
Ok cool. Happy to release it now?

**Comment by dwdowns** [comment]
Yes thank you 😊

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Pull request merged**
