### PR TITLE
Allow administrators to hide vendors

### PR DESCRIPTION
**Pull request by johndowns**

### CODE REVIEW

**Comment by JackDownsNZ** [comment]
Looks like it works from my testing! Have just noticed you've done the hiding from vendors on the backend side so will just remove my version of it - then im happy with it.

**Comment by JackDownsNZ** [comment]
One thing - probably unavoidable, if the vendor (user) is already on the Business page (or goes directly to the link/ has it bookmarked) prior to the admin hiding it. The user can still access it.

**Comment by johndowns** [comment]
Given the use case I think this is ok

**Comment by johndowns** [comment]
@JackDownsNZ This is looking good to me. Can you approve if you are happy for it to be merged from your side?

**Pull request merged**
